name: "Update khinsider index"
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  index-sync:
    name: index-sync
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.2

      - run: go install github.com/marcus-crane/khinsider/v2@v2.0.0-alpha1

      - run: go run main.go index

      - run: cp ~/.khinsider/index.json .

      - name: Commit index changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux

          git config --local user.email "helper@utf9k.net"
          git config --local user.name "Indexer Bot"

          git add .
          git commit -a -m "Index has been updated" || exit 0

          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${remote_repo}" HEAD:main
